# This is an example workflow showing how other repositories can use this action
# Copy this file to your repository's .github/workflows/ directory

name: Example External Usage

# This workflow is disabled by default - remove the condition to enable it
on:
  workflow_dispatch:
    inputs:
      enable_example:
        description: 'Enable this example workflow'
        required: true
        type: boolean
        default: false

jobs:
  example-sync-test:
    if: github.event.inputs.enable_example == 'true'
    runs-on: ubuntu-latest
    
    steps:
      # Example 1: Basic usage
      - name: Basic sync test
        uses: ethpandaops/kurtosis-sync-test@main
        with:
          network: mainnet
          el_client: geth
          cl_client: lighthouse
      
      # Example 2: Custom configuration
      - name: Custom sync test
        uses: ethpandaops/kurtosis-sync-test@main
        with:
          enclave_name: my-custom-test
          network: sepolia
          el_client: nethermind
          cl_client: teku
          wait_time: 3600
  
  matrix-example:
    if: github.event.inputs.enable_example == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - network: mainnet
            el_client: geth
            cl_client: lighthouse
          - network: sepolia
            el_client: reth
            cl_client: prysm
    
    steps:
      - name: Matrix sync test
        uses: ethpandaops/kurtosis-sync-test@main
        with:
          network: ${{ matrix.network }}
          el_client: ${{ matrix.el_client }}
          cl_client: ${{ matrix.cl_client }}

  pages-example:
    if: github.event.inputs.enable_example == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Sync test with Pages deployment
        uses: ethpandaops/kurtosis-sync-test@main
        id: sync-test
        with:
          network: mainnet
          el_client: geth
          cl_client: lighthouse
          generate_html_report: 'true'
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4