name: Sync Test

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to test'
        required: true
        type: choice
        options:
          - fusaka-devnet-1
          - mainnet
          - sepolia
          - hoodi
        default: 'fusaka-devnet-1'
      
      el_client:
        description: 'Execution layer client'
        required: true
        type: choice
        options:
          - geth
          - nethermind
          - reth
          - besu
          - erigon
        default: 'geth'
      
      cl_client:
        description: 'Consensus layer client'
        required: true
        type: choice
        options:
          - lighthouse
          - teku
          - prysm
          - nimbus
          - lodestar
          - grandine
        default: 'lighthouse'
      
      wait_time:
        description: 'Wait time in seconds before restarting clients'
        required: false
        type: number
        default: 1800
      
      enclave_name:
        description: 'Custom enclave name (optional)'
        required: false
        type: string
  
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'

# Allow only one concurrent deployment, skipping runs queued between the one in-progress and latest queued.
concurrency:
  group: "sync-test"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(github.event_name == 'workflow_dispatch' && '[{"network":"manual","el_client":"manual","cl_client":"manual"}]' || '[{"network":"fusaka-devnet-1","el_client":"geth","cl_client":"lighthouse"},{"network":"fusaka-devnet-1","el_client":"nethermind","cl_client":"teku"},{"network":"fusaka-devnet-1","el_client":"reth","cl_client":"lighthouse"},{"network":"fusaka-devnet-1","el_client":"besu","cl_client":"teku"}]') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set matrix values for manual runs
        id: matrix
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "network=${{ github.event.inputs.network }}" >> $GITHUB_OUTPUT
            echo "el_client=${{ github.event.inputs.el_client }}" >> $GITHUB_OUTPUT
            echo "cl_client=${{ github.event.inputs.cl_client }}" >> $GITHUB_OUTPUT
            echo "wait_time=${{ github.event.inputs.wait_time }}" >> $GITHUB_OUTPUT
            echo "enclave_name=${{ github.event.inputs.enclave_name }}" >> $GITHUB_OUTPUT
          else
            echo "network=${{ matrix.network }}" >> $GITHUB_OUTPUT
            echo "el_client=${{ matrix.el_client }}" >> $GITHUB_OUTPUT
            echo "cl_client=${{ matrix.cl_client }}" >> $GITHUB_OUTPUT
            echo "wait_time=1800" >> $GITHUB_OUTPUT
            echo "enclave_name=" >> $GITHUB_OUTPUT
          fi
      
      - name: Run sync test
        uses: ./
        id: sync-test
        with:
          network: ${{ steps.matrix.outputs.network }}
          el_client: ${{ steps.matrix.outputs.el_client }}
          cl_client: ${{ steps.matrix.outputs.cl_client }}
          wait_time: ${{ steps.matrix.outputs.wait_time }}
          enclave_name: ${{ steps.matrix.outputs.enclave_name }}
          generate_html_report: 'false'
          save_to_data_branch: 'true'  # Always save results
          config_file: ${{ steps.matrix.outputs.network == 'fusaka-devnet-1' && 'devnet-templates/devnet-template.yaml' || '' }}
      
      
      - name: Display test summary
        run: |
          echo "## Sync Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Network:** ${{ steps.matrix.outputs.network }}" >> $GITHUB_STEP_SUMMARY
          echo "**EL Client:** ${{ steps.matrix.outputs.el_client }}" >> $GITHUB_STEP_SUMMARY
          echo "**CL Client:** ${{ steps.matrix.outputs.cl_client }}" >> $GITHUB_STEP_SUMMARY
          echo "**Result:** ${{ steps.sync-test.outputs.test_result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Summary:** ${{ steps.sync-test.outputs.test_summary }}" >> $GITHUB_STEP_SUMMARY
          echo "**Enclave:** ${{ steps.sync-test.outputs.enclave_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View historical results at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY